#! /usr/bin/env python

# 2520 is the smallest number that can be divided by each of the
# numbers from 1 to 10 without any remainder.

# What is the smallest positive number that is evenly divisible by all
# of the numbers from 1 to 20?

from toolbox.euler.factor import lcm

def main():
    assert lcm(1,2,3,4,5,6,7,8,9,10) == 2520
    print(lcm(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))

    return

if __name__ == "__main__":
    main()
