#! /usr/bin/env python

# A palindromic number reads the same both ways. The largest
# palindrome made from the product of two 2-digit numbers is 9009 = 91
# × 99.

# Find the largest palindrome made from the product of two 3-digit
# numbers.

import itertools

def is_palindrome(num):
    num_chars = list(str(num))
    return num_chars == list(reversed(num_chars))

def main():

    mult = lambda xy: xy[0]*xy[1]

    print(
        max(
            filter(
                is_palindrome,
                map(mult, itertools.product(range(100, 1000),range(100, 1000)))
            )
        )
    )
    return

if __name__ == "__main__":
    main()
