#! /usr/bin/env python


# The sum of the squares of the first ten natural numbers is,n

# The square of the sum of the first ten natural numbers is,

# Hence the difference between the sum of the squares of the first ten
# natural numbers and the square of the sum is

# Find the difference between the sum of the squares of the first one
# hundred natural numbers and the square of the sum.

def main():
    assert sum(range(1,11))**2 - sum([x**2 for x in range(1,11)]) == 2640
    print(sum(range(1,101))**2 - sum([x**2 for x in range(1,101)]))
    return

if __name__ == "__main__":
    main()
