#! /usr/bin/env python



# By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we
# can see that the 6th prime is 13.

# What is the 10001st prime number?

from toolbox.euler.primes.sieve import sieve

def main():
    primes = sieve(104759)
    print(primes[10000])
    return

if __name__ == "__main__":
    main()
