#! /usr/bin/env python


# The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
# Find the sum of all the primes below two million.


from toolbox.euler.primes.sieve import sieve


def main():

    print(sum(sieve(2000000)))

    return

if __name__ == "__main__":
    main()
