#! /usr/bin/env python
""" Test imports
"""
__author__ = "naddy@energy-solution.com"

import logging
from argparse import ArgumentParser

app_name = "test_code"
DEFAULT_LOG_FORMAT = "%(levelname)s - %(message)s"
log = logging.getLogger(app_name)

def main():
    import toolbox
    import toolbox.aoc

    return

if __name__ == "__main__":

    arg_parser = ArgumentParser()
    arg_parser.add_argument('-v', '--verbose', action='count', default=0)
    arg_parser.add_argument("--log-format", default=DEFAULT_LOG_FORMAT)

    args = arg_parser.parse_args()

    log_levels = [logging.WARNING, logging.INFO, logging.DEBUG]
    log_level = log_levels[min(len(log_levels) - 1, args.verbose)]  # capped to number of levels
    logging.basicConfig(level=log_level, format=args.log_format)

    main()
